//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwainDirectApplication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwainDirectApplication.WinFormStrings", typeof(WinFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string strButtonClose {
            get {
                return ResourceManager.GetString("strButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string strButtonOpen {
            get {
                return ResourceManager.GetString("strButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register....
        /// </summary>
        internal static string strButtonRegisterEllipsis {
            get {
                return ResourceManager.GetString("strButtonRegisterEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string strButtonScan {
            get {
                return ResourceManager.GetString("strButtonScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        internal static string strButtonSelectEllipsis {
            get {
                return ResourceManager.GetString("strButtonSelectEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup....
        /// </summary>
        internal static string strButtonSetupEllipsis {
            get {
                return ResourceManager.GetString("strButtonSetupEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string strButtonStop {
            get {
                return ResourceManager.GetString("strButtonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister....
        /// </summary>
        internal static string strButtonUnregisterEllipsis {
            get {
                return ResourceManager.GetString("strButtonUnregisterEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWAIN Direct: Application.
        /// </summary>
        internal static string strFormScanTitle {
            get {
                return ResourceManager.GetString("strFormScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Scanner.
        /// </summary>
        internal static string strFormSelectTitle {
            get {
                return ResourceManager.GetString("strFormSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Scan Session.
        /// </summary>
        internal static string strFormSetupTitle {
            get {
                return ResourceManager.GetString("strFormSetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image destination.
        /// </summary>
        internal static string strGroupboxSelectImageDestination {
            get {
                return ResourceManager.GetString("strGroupboxSelectImageDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image destination folder:.
        /// </summary>
        internal static string strLabelSelectImageDestination {
            get {
                return ResourceManager.GetString("strLabelSelectImageDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select scanner:.
        /// </summary>
        internal static string strLabelSelectScanner {
            get {
                return ResourceManager.GetString("strLabelSelectScanner", resourceCulture);
            }
        }
    }
}
