//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwainDirect.Scanner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang_fr_FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_fr_FR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwainDirect.Scanner.lang_fr_FR", typeof(lang_fr_FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close the &apos;TWAIN Direct on TWAIN Bridge&apos; program?.
        /// </summary>
        public static string errCloseTwainBridge {
            get {
                return ResourceManager.GetString("errCloseTwainBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for scanners....
        /// </summary>
        public static string errLookingForScanners {
            get {
                return ResourceManager.GetString("errLookingForScanners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we do not have a cloud manager for this cloud..
        /// </summary>
        public static string errNoCloudManager {
            get {
                return ResourceManager.GetString("errNoCloudManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scanners found..
        /// </summary>
        public static string errNoScannersFound {
            get {
                return ResourceManager.GetString("errNoScannersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to select a TWAIN driver?  If so, please make sure your scanner is powered on and connected, and press YES..
        /// </summary>
        public static string errRegisterTwainDriver {
            get {
                return ResourceManager.GetString("errRegisterTwainDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are unable to use the selected scanner.  Please make sure your scanner is turned on and connected before trying again..
        /// </summary>
        public static string errUnableToUseScanner {
            get {
                return ResourceManager.GetString("errUnableToUseScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Cloud....
        /// </summary>
        public static string strButtonCloudRegisterEllipsis {
            get {
                return ResourceManager.GetString("strButtonCloudRegisterEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Cloud....
        /// </summary>
        public static string strButtonManageCloudEllipsis {
            get {
                return ResourceManager.GetString("strButtonManageCloudEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez le scanner....
        /// </summary>
        public static string strButtonRegisterEllipsis {
            get {
                return ResourceManager.GetString("strButtonRegisterEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Début.
        /// </summary>
        public static string strButtonStart {
            get {
                return ResourceManager.GetString("strButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêt.
        /// </summary>
        public static string strButtonStop {
            get {
                return ResourceManager.GetString("strButtonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Local....
        /// </summary>
        public static string strButtonTwainLocalManagerEllipsis {
            get {
                return ResourceManager.GetString("strButtonTwainLocalManagerEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run this program when you log on.
        /// </summary>
        public static string strCheckboxRunOnLogin {
            get {
                return ResourceManager.GetString("strCheckboxRunOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWAIN Direct on TWAIN Bridge.
        /// </summary>
        public static string strFormMainTitle {
            get {
                return ResourceManager.GetString("strFormMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current driver:.
        /// </summary>
        public static string strLabelCurrentDriver {
            get {
                return ResourceManager.GetString("strLabelCurrentDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current note:.
        /// </summary>
        public static string strLabelCurrentNote {
            get {
                return ResourceManager.GetString("strLabelCurrentNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;A propos.
        /// </summary>
        public static string strMenuAbout {
            get {
                return ResourceManager.GetString("strMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Sortie....
        /// </summary>
        public static string strMenuExit {
            get {
                return ResourceManager.GetString("strMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ouvrir.
        /// </summary>
        public static string strMenuShowConsole {
            get {
                return ResourceManager.GetString("strMenuShowConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select scanner driver:.
        /// </summary>
        public static string strSelectScannerDriver {
            get {
                return ResourceManager.GetString("strSelectScannerDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A note or friendly name for your scanner:.
        /// </summary>
        public static string strSetNote {
            get {
                return ResourceManager.GetString("strSetNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un programme permettant aux applications TWAIN Direct de communiquer avec les scanners pris en charge par les pilotes TWAIN..
        /// </summary>
        public static string strTextAbout {
            get {
                return ResourceManager.GetString("strTextAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current cloud:.
        /// </summary>
        public static string strTextCurrentCloud {
            get {
                return ResourceManager.GetString("strTextCurrentCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des scanners enregistrés...(veuillez attendre la liste).
        /// </summary>
        public static string strTextListingScannersBegin {
            get {
                return ResourceManager.GetString("strTextListingScannersBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste complète....
        /// </summary>
        public static string strTextListingScannersEnd {
            get {
                return ResourceManager.GetString("strTextListingScannersEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun scanners enregistré....
        /// </summary>
        public static string strTextNoScannersRegistered {
            get {
                return ResourceManager.GetString("strTextNoScannersRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program is being minimized to the system tray.  Please right-click on its icon there to close it..
        /// </summary>
        public static string strTextNotClosing {
            get {
                return ResourceManager.GetString("strTextNotClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start npm.
        /// </summary>
        public static string strTextNpmFailed {
            get {
                return ResourceManager.GetString("strTextNpmFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting &apos;npm start&apos;, we will wait 10 seconds for it to stabilize..
        /// </summary>
        public static string strTextStartNpm {
            get {
                return ResourceManager.GetString("strTextStartNpm", resourceCulture);
            }
        }
    }
}
